name: Build Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Conda Build Script
      run: |
        export PATH="$MINICONDA_PATH:$MINICONDA_SUB_PATH:$PATH"
        conda build conda_recipe -c conda-forge -c defaults
