name: Build Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: goanpeca/action-setup-conda@master
      with:
        conda-version: '4.8'         # optional. Version of conda to use for base evironment.
        conda-build-version: '3.17'  # optional. If not provided conda build is not installed.
    - name: Run Conda Build 
      run: |
        conda build conda_recipe -c conda-forge -c defaults
